name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create google-services from secret
        env:
          GOOGLE_SERVICES_JSON_CONTENT: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          TARGET_PATH="$GITHUB_WORKSPACE/app/google-services.json"
          TEMP_PATH="$GITHUB_WORKSPACE/app"
          echo "pwd: $(pwd)"
          echo "TEMP_PATH: $TEMP_PATH"
          echo "TARGET_PATH: $TARGET_PATH"
          if [ -d $GITHUB_WORKSPACE ]; then
            echo "Directory $GITHUB_WORKSPACE exists."
          else
            echo "Directory $GITHUB_WORKSPACE doesn't exist."
          fi
          if [ -d $TEMP_PATH ]; then
            echo "Directory $TEMP_PATH exists."
          else
            echo "Directory $TEMP_PATH doesn't exist."
          fi
          if [ -n "$GOOGLE_SERVICES_JSON_CONTENT" ]; then
            echo "Creating $TARGET_PATH"
            echo "$GOOGLE_SERVICES_JSON_CONTENT" > $TARGET_PATH
          else
            echo "GOOGLE_SERVICES_JSON secret not found. Exiting build"
            exit 1
          fi
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Run tests
      - name: Run tests
        run: ./gradlew test

      # Check code style
      - name: Check code style
        run: ./gradlew check

      # Generate coverage report
      - name: Generate coverage report
        run: ./gradlew jacocoTestReport

      # Enforce minimum coverage
      - name: Enforce minimum coverage
        run: |
          COVERAGE=$(grep -oP 'TOTAL.*\K\d+\.\d+' build/reports/jacoco/test/jacocoTestReport.csv)
          MIN_COVERAGE=80.0
          if (( $(echo "$COVERAGE < $MIN_COVERAGE" | bc -l) )); then
            echo "Code coverage ($COVERAGE%) is below the minimum threshold ($MIN_COVERAGE%)."
            exit 1
          fi
